name: Playwright SDK Wrapper
on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
  PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
  LT_SDK_DEBUG: true
  SMARTUI_DEBUG: true

jobs:
  smartui-playwright-sdk:
  
    name: Execute playwright sdk build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create commit status
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: |
          API_HOST=https://api.github.com
          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          git checkout $GITHUB_HEAD_REF
          COMMIT_ID=$(git rev-parse HEAD)
          echo "Last commit ID of PR: $COMMIT_ID"
          REF=$GITHUB_SHA
          echo "Current Commit ID REF : $REF"
          GITHUB_URL=$API_HOST/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_ID
          echo "GITHUB_URL: $GITHUB_URL"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies and clean directory
        run: |
          npm i @lambdatest/smartui-cli @lambdatest/playwright-driver playwright


      - name: Execute playwright wrapper
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui exec node sdk/playwrightCloud.js --config smartui-web.json
